# Generated by Django 4.2.3 on 2024-01-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketgroup',
            name='has_types',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketgroup',
            name='icon_id',
            field=models.IntegerField(default=0),
        ),
    ]
