# Generated by Django 4.2.3 on 2024-01-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_marketgroup_has_types_marketgroup_icon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketgroup',
            name='icon_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='marketgroup',
            name='parent_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
