# Generated by Django 4.2.3 on 2024-01-25 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_marketgroup_icon_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.IntegerField(default=0)),
                ('item_id', models.BigIntegerField(default=0)),
                ('location_id', models.BigIntegerField(default=0)),
                ('location_type', models.CharField(max_length=200, null=True)),
                ('location_flag', models.CharField(max_length=200, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.invtype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('type', 'location_id'), name='unique_asset_constraint'),
        ),
    ]
