# Generated by Django 4.2.9 on 2024-02-11 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('inventory', '0004_asset_asset_unique_asset_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.invtype'),
        ),
        migrations.DeleteModel(
            name='InvType',
        ),
        migrations.DeleteModel(
            name='MarketGroup',
        ),
    ]
